## 1.

In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.2'

In [3]:
print(np.__config__)
np.show_config()

<module 'numpy.__config__' from '/usr/local/miniconda3/lib/python3.6/site-packages/numpy/__config__.py'>
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_opt_info:
    extra_compile_args = ['-msse3', '-I/System/Library/Frameworks/vecLib.framework/Headers']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
openblas_clapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_opt_info:
    extra_compile_args = ['-msse3']
    extra_link_args = ['-Wl,-framework', '-Wl,Accelerate']
    define_macros = [('NO_ATLAS_INFO', 3), ('HAVE_CBLAS'

In [4]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
z.size , z.itemsize, z.nbytes

(10, 8, 80)

In [6]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [7]:
a = np.zeros(10)
a[4] = 1

In [8]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:
z = np.arange(10, 50)
z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [10]:
z = np.arange(9).reshape(3, 3)
z

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4]),)

In [12]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.random((3, 3, 3))

array([[[0.29304811, 0.12673871, 0.43767644],
        [0.5781495 , 0.22962305, 0.08603147],
        [0.91517044, 0.40777553, 0.27787132]],

       [[0.63551905, 0.54468935, 0.98639421],
        [0.64617995, 0.70061911, 0.81598195],
        [0.13455335, 0.79966203, 0.22837449]],

       [[0.15437582, 0.09116922, 0.03606127],
        [0.88164732, 0.54108974, 0.74833609],
        [0.55212253, 0.06842035, 0.94458618]]])

In [14]:
z = np.random.random((10, 10))
np.max(z), np.min(z)

(0.9719337541304568, 0.0011057731467042364)

In [15]:
z = np.random.random(30)
z.shape, z.mean()

((30,), 0.559923189733492)

15 TODO

In [16]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
Z = np.ones((10,10))
r, c = Z.shape
z = np.zeros((r+2, c+2))
z[1:-1,1:-1] = Z
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

16 TODO

In [18]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [19]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf < np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [20]:
np.diag([1, 2, 3, 4], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [21]:
np.asarray([np.roll(np.tile([0, 1], 4),  i) for i in range(8)])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [22]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

In [25]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [27]:
x = np.random.random((5, 5))
norm = np.linalg.norm(x, axis=1)
x / norm

array([[0.28291261, 0.59591255, 0.14747607, 0.41107751, 0.8724659 ],
       [0.49352635, 0.42342898, 0.30611658, 0.10704234, 0.65049468],
       [0.1806118 , 0.75120556, 0.64705917, 0.62103074, 0.07257182],
       [0.46295862, 0.32458296, 0.29102567, 0.53505738, 0.11113563],
       [0.60901101, 0.01377011, 0.21525614, 0.41623665, 0.47193049]])

In [28]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[0.50404444 0.71749101 0.86557049 0.41947106 0.95187662]
 [0.63024147 0.43782303 0.         0.1201496  0.01381654]
 [0.92968168 0.68608452 0.04384727 0.62792903 0.47454506]
 [0.89594298 0.88471235 0.4959825  0.62423151 0.07673428]
 [1.         0.4070428  0.83274943 0.12331121 0.45410343]]


In [29]:
dt = np.dtype([('R','u1'), ('G','u1'), ('B','u1'), ('A','u1')])

In [30]:
a = np.random.random((5, 3))
b = np.random.random((3, 2))
a.dot(b)

array([[1.31770174, 0.87666566],
       [0.45950099, 0.47452116],
       [0.84395671, 0.55795319],
       [0.69695761, 0.22364838],
       [0.65991658, 0.33877829]])

In [32]:
z = np.arange(10)
z[2:9] = np.negative(z[2:9])
z

array([ 0,  1, -2, -3, -4, -5, -6, -7, -8,  9])

In [33]:
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


In [35]:
Z = np.arange(10)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
 # Z<Z>Z # legal

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])